// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBrpzxN35X_ZX2iKc3J0Pa8faMMnoTB4',
    appId: '1:816801790796:web:09508890150cd603822de9',
    messagingSenderId: '816801790796',
    projectId: 'message-64a5a',
    authDomain: 'message-64a5a.firebaseapp.com',
    storageBucket: 'message-64a5a.firebasestorage.app',
    measurementId: 'G-74HL25ZECY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlH5Tn0Av5k1GBpG7kFS8HI7M9Yl0yXQ',
    appId: '1:816801790796:android:3b4402343e8798fb822de9',
    messagingSenderId: '816801790796',
    projectId: 'message-64a5a',
    storageBucket: 'message-64a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTRMMKzhd42JQnzbMBu9qE0XiUulcuB8',
    appId: '1:816801790796:ios:5d1eb0f314ace075822de9',
    messagingSenderId: '816801790796',
    projectId: 'message-64a5a',
    storageBucket: 'message-64a5a.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );
}
